### ISSUE TITLE
Develop a user-user CF model for MovieLen1M

### ISSUE THREAD

**Issue by ytann** [ytann/Recommendation_Engine#1]
Write your own code. You can take help from [here](https://medium.com/sfu-big-data/recommendation-systems-user-based-collaborative-filtering-using-n-nearest-neighbors-bf7361dc24e0).

**Comment by sudip10028** [comment]
what exactly  we have to do in this  PS?
I want to work on this.

**Comment by shreyasirc** [comment]
I would like to work on this issue

**Comment by tista123** [comment]
I would like to contribute to this issue

**Comment by ytann** [comment]
I was a bit late in assigning the task to @tista123. @shreyasirc, and @Sudip123Chakraborty  I'd suggest working on other issues as only one would submission would count. I have added some more issues, try them out.

**Comment by ytann** [comment]
@tista123, thank you for your contribution.
