### ISSUE TITLE
Develop item-item CF model for MovieLen1M

### ISSUE THREAD

**Issue by ytann** [ytann/Recommendation_Engine#2]
Write your own code. You can take help from [here](https://en.wikipedia.org/wiki/Item-item_collaborative_filtering) and [here](https://medium.com/sfu-big-data/recommendation-systems-user-based-collaborative-filtering-using-n-nearest-neighbors-bf7361dc24e0).

**Comment by AdarshKumar712** [comment]
What exactly we need to output in this recommendation system? 
Like the top 5 movie recommendations or something similar??
I am currently working on this issue

**Comment by ytann** [comment]
Since this is an item item CF, for starters, we'll give a movie name and it has to suggest top n users who would be interested in that movie. 
You can take n accordingly.

**Comment by ytann** [comment]
Thank you @AdarshKumar712 for your contribution.
